### ISSUE TITLE
Deck management UI design

### ISSUE THREAD

**Issue by AndersenJ** [Cameron637/flash-card-shattered-pixel-dungeon#12]
KC needs to make a UI design mockup for deck management. This includes things like importing a new deck, deleting an old deck, or selecting which decks are active.

**Comment by Chandler-Eady** [comment]
![deck-management](https://user-images.githubusercontent.com/55124176/68617240-19025980-0484-11ea-8518-238f8c9533d6.png)
![image (3)](https://user-images.githubusercontent.com/55124176/68617241-1a338680-0484-11ea-90f5-c4b56c7bafa3.png)
Here are a few of the images that KC posted to the Slack channel

**Comment by Chandler-Eady** [comment]
The UI has been designed, the only part I think may still need to be done is disabling leaving this screen if no decks are currently selected.
