### ISSUE TITLE
Flashcard event implementation

### ISSUE THREAD

**Issue by AndersenJ** [Cameron637/flash-card-shattered-pixel-dungeon#15]
We need to implement the flashcard question prompt event based off of what KC designs.

**Comment by Cameron637** [comment]
The logic for this is mostly done with #23, it just needs to be modified to fit the designs and hook into real flash card decks.

**Comment by Chandler-Eady** [comment]
@AndersenJ mentioned that Strength/Upgrade aren't nearly the only game-breaking effects out there and threw out there that maybe we needed to redesign how we're working with flash-card events. If that's the case, then this event should remain open. If not, I think this issue should probably be marked as closed.

**Comment by Chandler-Eady** [comment]
However, I would like to note that at the current time, answering the flash-card correctly "gives" the player a scroll/potion of the appropriate type. Do we want to skip that stage and go straight to applying the effect?

**Comment by Chandler-Eady** [comment]
The flow has been better refined now with reading the card, answering the question, choosing potion or scroll, and choosing an effect. No item is given, instead default actions are used.
