### ISSUE TITLE
[Medium] - Mystical Card producing unexpected player buff - 10/31

### ISSUE THREAD

**Issue by jacobgropp** [Cameron637/flash-card-shattered-pixel-dungeon#16]
Description:
Using the imported "Korean Language" deck about 1/3rd of all mystical cards state a specific player buff will be given upon a correct answer but instead a different buff is given. This occurs each time the "Korean Language" deck is imported. 

Steps to Reproduce Error: 
Simply import the "Koran Language" deck and the error happens every time. 

Deadline:
10/31 or ASAP

**Comment by jacobgropp** [comment]
This is a bug reporting template for testing.

**Comment by Cameron637** [comment]
Closing this because I set up issue templates for feature requests and bug reports. If we want to change them we can just propose changes to those.
