### ISSUE TITLE
Make it so the mystical orbs can only reproduce identified scrolls/potions

### ISSUE THREAD

**Issue by NonPolynomialTim** [Cameron637/flash-card-shattered-pixel-dungeon#18]
Right now when you use a mystical orb you can choose any scroll or potion effect.  It may be worth making it so that they can only use the effects of identified scrolls/potions.

**Comment by AndersenJ** [comment]
What is your proposed behavior for a situation where no scrolls are identified?

Anyways, we definitely need to make it so that they can't act as a scroll of upgrade or potion of strength. That would totally break the game.

**Comment by Chandler-Eady** [comment]
I've split these comments into a feature request and a bug. See request https://github.com/Cameron637/flash-card-shattered-pixel-dungeon/issues/26 and bug https://github.com/Cameron637/flash-card-shattered-pixel-dungeon/issues/25.
