### ISSUE TITLE
Mystical Orbs can't properly utilize scrolls of upgrade

### ISSUE THREAD

**Issue by NonPolynomialTim** [Cameron637/flash-card-shattered-pixel-dungeon#22]
**Describe the bug**
When using mystical orbs as a scroll of upgrade the scroll does not get read, but is instead added to the player's inventory.

**To Reproduce**
Use a mystical orb as a scroll of upgrade.

**Expected behavior**
The orb should be consumed and the selected item should be upgraded.

**Comment by AndersenJ** [comment]
We probably don't want the mystical orb to be able to do this anyways, right? That would completely break the game.

**Comment by Chandler-Eady** [comment]
This has been decided to be a non-issue as scrolls of upgrade and potions of strength shouldn't be able to be imitated by the flashcards as it would be too game-breaking. See issue https://github.com/Cameron637/flash-card-shattered-pixel-dungeon/issues/25
