### ISSUE TITLE
Design and implement study question data structure

### ISSUE THREAD

**Issue by AndersenJ** [Cameron637/flash-card-shattered-pixel-dungeon#3]
We agreed that we would do Anki-style cards where we were asked a question, and we simply said whether or not we got it right. We do want to allow for things like multiple choice post-demo though.

**Comment by Chandler-Eady** [comment]
Implemented in the Interfaces branch for now

**Comment by AndersenJ** [comment]
I know this hasn't been merged in yet, but I think I'll branch off of your interfaces branch for now when doing my own work.
