### ISSUE TITLE
Main Menu Icon for Deck Management

### ISSUE THREAD

**Issue by Chandler-Eady** [Cameron637/flash-card-shattered-pixel-dungeon#34]
**Is your feature request related to a problem? Please describe.**
The icon on the menu for the "flashcard decks" option is currently just the icon for an individual card

**Describe the solution you'd like**
A custom sprite for a deck of cards would be ideal

**Describe alternatives you've considered**
Leaving the single flash-card wouldn't be terrible

**Comment by kadew** [comment]
![icons](https://user-images.githubusercontent.com/21695494/69003344-1311db80-08bd-11ea-99b8-543103153897.png)
New icon for main menu is here (and also on slack)
