### ISSUE TITLE
New main menu art

### ISSUE THREAD

**Issue by AndersenJ** [Cameron637/flash-card-shattered-pixel-dungeon#6]
KC needs to make new main menu art.

**Comment by Chandler-Eady** [comment]
![image (1)](https://user-images.githubusercontent.com/55124176/68617073-a2655c00-0483-11ea-8eb3-dca79dd41744.png)
![image (2)](https://user-images.githubusercontent.com/55124176/68617075-a3968900-0483-11ea-9711-ac8dc63a5d58.png)
Here are a couple images from KC

**Comment by Chandler-Eady** [comment]
Should I mark this one closed and create a new issue for attaching these images to the game? Or should I wait for them to be attached to close this issue?

**Comment by Chandler-Eady** [comment]
Finished, attached to the game, and work great
