### ISSUE TITLE
Come up with name for "Mystical Card" item

### ISSUE THREAD

**Issue by AndersenJ** [Cameron637/flash-card-shattered-pixel-dungeon#9]
Mystical Card isn't a terrible name, but it's possible that we can do better. Lets post suggestions here.

**Comment by Chandler-Eady** [comment]
I'm down for "Mystical Card", but maybe this is something for our narrative lead to decide?

**Comment by NonPolynomialTim** [comment]
@jacobgropp should probably weigh in here.  I've been working on it and I've been calling it a "mystical orb" and filling in some little text snippets in the menus about how some swirling clouds in the orb bend to your will to turn into a liquid (potion) or write words (scroll).  It would be really easy to change all of that though, and someone with better writing skills than mine should definitely rewrite them anyway even if we keep the same idea.

**Comment by jacobgropp** [comment]
I think "mystical card" is rather vague and doesn't give much definition to this game-play mod. I assume the flashcards will end up having a higher opportunity to drop over many other items as the primary reason someone plays with this mod is to study, correct? With that in mind I don't think "mystical card" works as the whole "mystical" aspect becomes rather bland and generic when you have picked up 10, 20, 30 of these cards throughout a game. 

What if the cards are an actual deck of cards (ace, spade, diamond, heart) that relates to the shattered pixel dungeon? We can build a story surrounding why they are there. Perhaps an adventurer lost a deck of cards in the dungeon long ago and now they are imbued with magical properties? This allows them to feel unique and meaningful in the game while also accomplishing what we want. This could also develop into a more organic, story-based focus (stretch goal of course) where the player's primary purpose for delving into the dungeon is in search of this mystical deck of cards and the bosses related to it. 

Now, all of this to say that ultimately I don't think it is entirely important what the class name in the code is as long as the name is malleable and changeable on the top end. Allow KC and I to interface with the code on the front-end. That is what will be seen by the player. What is happening within the code is not important to the player so don't get too bogged down in that. Looking at the architecture UML I notice there is no class that is called "Flashcard." Instead we have Mystical Card and that seems silly to me. We already have FlashDeck, FlashQuestion, and FlashWindow so just make the class Flashcard. This keeps it as simple as possible and provides the necessary infrastructure. For all intents and purposes, at the code level, this is a flashcard item. Nothing more nothing less. Create that simplicity first and we can later interface with the UI in different ways. 

Does that make sense or am I misinterpreting what you guys are asking?

**Comment by Chandler-Eady** [comment]
Did we decide on Mystical Card? Or are we keeping this one open?

**Comment by Chandler-Eady** [comment]
I should note here that we call it two different things in different places. It's either mystical card, or mystical orb. We should probably decide on only one.
